### PR TITLE
Type call function data and response

### PR DESCRIPTION
**Pull request by davestewart**
This PR types the `call()` function `data` and `response`:

```ts
// background
import { makeBus } from '../src'

import Tab = chrome.tabs.Tab

const bus = makeBus('content', {
  handlers: {
    tabs: {
      get ({ id }): Promise<Tab> {
        return chrome.tabs.get(id)
      }
    }
  }
})
```
```ts
// some other process

// existing bus
bus.call<Tab, { id: number }>('tabs/get', { id: 1 }).then(tab => {
  if (tab) {
    console.log(tab.url)
  }
})
```

This PR doesn't intend to provide any type safety between the handlers and the call, but allows a user to type the call parameters / return itself.

@oliverdunk - does this answer your request?

### CODE REVIEW

**Comment by oliverdunk** [comment]
This is great!

> This PR doesn't intend to provide any type safety between the handlers and the call

I think that would be nice eventually (when I've worked on things like this before, I've used an object with message names mapped to request and response types) which you can index into to provide this. I understand not being able to have everything on day one though 😅

**Comment by davestewart** [comment]
> I've used an object with message names mapped to request and response types

Nuxt has an automatic way of building types from source code, which it compiles into a definition file.

I'm not 100% on this, but from what I've seen elsewhere, suspect the solution might like in some level of AST traversal and augmenting core types?

```ts
// bus, somewhere in source code
export const bus = makeBus ('content', {
  handlers: {
    tabs: {
      get (id: number) { ... },
      remove (id: number) {... },
    }
  }
})
```

```ts
// generated output (pseudo-code)
declare module 'extension-bus' {
  export interface Bus {
    call (path: 'tabs/get', data: number): Promise<Tab>
    call (path: 'tabs/remove', data: number): Promise<void>
    ...
  }
}
```

```ts
// other process
bus.call('tabs/get', value) // <-- autocomplete here
```

But I'm outside my comfort zone here. Would need to get more input

**Comment by davestewart** [comment]
@oliverdunk I explored some options with Chat GPT:

https://chat.openai.com/share/d1560171-e884-4d2b-946f-7f75f72dc4cc

I've checked some of it, but not all of it.

Will do that in the next week or so (have to get on with other work now!)

If you have any thoughts / feedback, it would be very welcome.

**Comment by oliverdunk** [comment]
Just read through that conversation - really cool how it slowly built up the solution. I personally think the end result is really nice, at least as something to support optionally for developers that want it.

**Comment by davestewart** [comment]
OK! I can confirm that the augmentation to add paths, payloads and response types works:

image

I'm going to move this conversation to an issue so feel free to make any input there:

- #5

Meantime, I'll merge this :)

**Comment by davestewart** [comment]
Closing in favour of #7

**Pull request closed without merging**
